### PR TITLE
Refactor Code, Implement ViewBinding & Hilt

### PR DESCRIPTION
**Pull request by naufalprakoso**
What I've done?
1. Refactor Code
2. Implement ViewBinding
3. Implement Hilt

### CODE REVIEW

**Comment by mukul500** [comment]
Oh Thanks man. I didn't have time to implement databinding to this. You saved a lot of time by implementing this. I don't know dagger stuff so i have to look at it how it is working.

**Comment by naufalprakoso** [comment]
No problem. If you have any concerns or suggestions, don't hesitate to call me.

**Comment by mukul500** [comment]
So for Currently, I am putting your pull request on hold. So I can understand what's happening

**Comment by mukul500** [comment]
@naufalprakoso You implemented view binding. Kotlin Doesn't require viewBinding it automatically generates Views reference by their id. so we can access it directly. View binding is only useful if coupled with data binding

**Comment by naufalprakoso** [comment]
@mukul500 If you use DataBinding, you can to not use ViewBinding. And if you use ViewBinding, you can to not use DataBinding. DataBinding and ViewBinding are two different binding ways, but you can use both libraries in the same module and work together.

ViewBinding will generate a binding object for each layout in a module. It can give you the ability to replace `findViewById` or `Kotlin Synthetic`.

Why we ViewBinding Kotlin Synthetic?
[You can open binding comparison here](https://miro.medium.com/max/1400/1*APXv8swJYGv2O8CAqV1jLQ.png)

Reference:
- https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc

**Comment by mukul500** [comment]
Ok I will look at it.

**Comment by mukul500** [comment]
Hey join our discord #76 so i can personally talk with you there

**Comment by naufalprakoso** [comment]
Actually, I never use discord before 😅. Do you have any messenger?

**Comment by mukul500** [comment]
I have created a new branch for view binding please make pull request to that branch

**Comment by naufalprakoso** [comment]
How about Hilt?

**Comment by mukul500** [comment]
yeah include hilt also. Just create a new pull req to new branch i have created

**Comment by naufalprakoso** [comment]
Okay, I already change the base branch

**Comment by naufalprakoso** [comment]
Thank you @mukul500 🔥

**Comment by mukul500** [comment]
@naufalprakoso can u implement data binding also

**Comment by naufalprakoso** [comment]
Sure, next time I'll help you to implement Data Binding

**Pull request merged**
