### PR TITLE
Fixed Server Error

### PR DESCRIPTION
**Pull request by pokurt**
Hi mukul, sorry i was late but here to make things easy for you. i hope this pr would help among all users for this app and forks in future, if gogoanime gets an update ill try to do my best at opening pr fast

### CODE REVIEW

**Comment by Shemmy3** [comment]
Can you share your build of the fixed app ?

**Comment by DerrenTuscano** [comment]
@mukul500 the server error is still coming in my device

**Comment by kira910** [comment]
Do i have to uninstall and install it?

**Comment by ShujianDou** [comment]
Shouldn't it be goload now?

**Comment by pokurt** [comment]
> Shouldn't it be goload now?

it is. gonna add the commit

**Comment by pokurt** [comment]
> Can you share your build of the fixed app ?

fork is not maintained by @mukul500 ... but you can visit anime.pokurt.me to get the app

**Pull request closed without merging**
