### PR TITLE
Fix server error

### LINKED ISSUE #102: Server error
Im having a server error on every episode plzz help
Screenshot_2020-08-17-16-21-55-042_net xblacky animexstream

### PR DESCRIPTION
**Pull request by zeeshanhussain**
Fixed #102 , #101 , #100 etc.

You can get the apk from 
https://drive.google.com/file/d/1Em7BggvfIvMUI5ib964MafOOT-xs36uR/view?usp=sharing arm64

https://drive.google.com/file/d/18e3dPXUrvRIgOxrSdicurxEarWpkiE67/view?usp=sharing armeabi v7a

 https://drive.google.com/file/d/1Vmqh3jTdQPUus5mRwHWoijDo1krivyGy/view?usp=sharing x86_64

https://drive.google.com/file/d/1Yj_oyf9OwOfVoZcnwDHbe0r6DUag5jeZ/view?usp=sharing x86

https://drive.google.com/file/d/1UXwoubkRINtPI9Wcqr4RpwgCs7gFr__s/view?usp=sharing universal

### CODE REVIEW

**Comment by Giosel** [comment]
It says not found

**Comment by zeeshanhussain** [comment]
@Giosel try this https://drive.google.com/file/d/1Em7BggvfIvMUI5ib964MafOOT-xs36uR/view?usp=sharing.

**Comment by Greeencobra** [comment]
Is there anyway to get this for a non-arm64 release of this? I.e armeabi v7a? I'd like to be able to use this, but this is a different version to what I have so it won't install the patch properly

**Comment by zeeshanhussain** [comment]
@Greeencobra  Here is the armeabi v7a apk https://drive.google.com/file/d/18e3dPXUrvRIgOxrSdicurxEarWpkiE67/view?usp=sharing

**Comment by Greeencobra** [comment]
Odd, it keeps saying app not installed, even though it's the same version as the app I have

**Comment by zeeshanhussain** [comment]
@Greeencobra you have to uninstall the previous version,because both these apps are signed with a different key.

**Comment by Greeencobra** [comment]
Ah thanks, it's working

**Comment by vinaydwivedi01** [comment]
> @Greeencobra Here is the armeabi v7a apk https://drive.google.com/file/d/18e3dPXUrvRIgOxrSdicurxEarWpkiE67/view?usp=sharing

Can you please provide like "x86 or x86_64 apk" release because armeabi v7a don't seem to work on my device it always says "app not installed " error

**Comment by vinaydwivedi01** [comment]
> @Giosel try this https://drive.google.com/file/d/1Em7BggvfIvMUI5ib964MafOOT-xs36uR/view?usp=sharing.

Can you please provide like "x86 or x86_64 apk" release because armeabi v7a don't seem to work on my device it always says "app not installed " error

**Comment by vinaydwivedi01** [comment]
> Fixed #102 , #101 , #100 etc.
> 
> You can get apk from https://drive.google.com/file/d/1Em7BggvfIvMUI5ib964MafOOT-xs36uR/view?usp=sharing

Can you please provide like "x86 or x86_64 apk" release because armeabi v7a don't seem to work on my device it always says "app not installed " error

**Comment by zeeshanhussain** [comment]
> 
> Can you please provide like "x86 or x86_64 apk" release because armeabi v7a don't seem to work on my device it always says "app not installed " error

@vinaydwivedi01 https://drive.google.com/file/d/1Vmqh3jTdQPUus5mRwHWoijDo1krivyGy/view?usp=sharing x86_64

https://drive.google.com/file/d/1Yj_oyf9OwOfVoZcnwDHbe0r6DUag5jeZ/view?usp=sharing x86

**Comment by vinaydwivedi01** [comment]
> > Can you please provide like "x86 or x86_64 apk" release because armeabi v7a don't seem to work on my device it always says "app not installed " error
> 
> @vinaydwivedi01 https://drive.google.com/file/d/1Vmqh3jTdQPUus5mRwHWoijDo1krivyGy/view?usp=sharing x86_64
> 
> https://drive.google.com/file/d/1Yj_oyf9OwOfVoZcnwDHbe0r6DUag5jeZ/view?usp=sharing x86

i don't but it still says app not installed , thanks anyways

**Comment by zeeshanhussain** [comment]
@vinaydwivedi01 you have to uninstall the previous app before installing this.

**Comment by vinaydwivedi01** [comment]
> @vinaydwivedi01 you have to uninstall the previous app before installing this.

have you got any like "AnimexStream-v0.2.2-universal-release.apk" only that did work on my device with the app last time

**Comment by vinaydwivedi01** [comment]
> @vinaydwivedi01 you have to uninstall the previous app before installing this.

i have already uninstalled the previous app versions , i think this is a compatibility issue, "can you provide universal-release apk" only that did work on my device the last time i installed it.

**Comment by zeeshanhussain** [comment]
> i have already uninstalled the previous app versions , i think this is a compatibility issue, "can you provide universal-release apk" only that did work on my device the last time i installed it.

@vinaydwivedi01 Here is the universal apk https://drive.google.com/file/d/1UXwoubkRINtPI9Wcqr4RpwgCs7gFr__s/view?usp=sharing

**Comment by vinaydwivedi01** [comment]
> > i have already uninstalled the previous app versions , i think this is a compatibility issue, "can you provide universal-release apk" only that did work on my device the last time i installed it.
> 
> @vinaydwivedi01 Here is the universal apk https://drive.google.com/file/d/1UXwoubkRINtPI9Wcqr4RpwgCs7gFr__s/view?usp=sharing

It didn't run on my device, but i tested it on another device it works fine. i guess the issue is with my device compatibility.
it works fine with AnimexStream-v0.2.1-universal-release which i installed earlier.
Device name - Moto E3 power 
Operating sys - Marshmallow 
Instruction Sets - aemeabi-v7a , armeabi

**Comment by vinaydwivedi01** [comment]
> > i have already uninstalled the previous app versions , i think this is a compatibility issue, "can you provide universal-release apk" only that did work on my device the last time i installed it.
> 
> @vinaydwivedi01 Here is the universal apk https://drive.google.com/file/d/1UXwoubkRINtPI9Wcqr4RpwgCs7gFr__s/view?usp=sharing

It didn't run on my device, but i tested it on another device it works fine. i guess the issue is with my device compatibility.
it works fine with AnimexStream-v0.2.2-universal-release which i installed earlier.
Device name - Moto E3 power
Operating sys - Marshmallow
Instruction Sets - aemeabi-v7a , armeabi

**Comment by vinaydwivedi01** [comment]
> > i have already uninstalled the previous app versions , i think this is a compatibility issue, "can you provide universal-release apk" only that did work on my device the last time i installed it.
> 
> @vinaydwivedi01 Here is the universal apk https://drive.google.com/file/d/1UXwoubkRINtPI9Wcqr4RpwgCs7gFr__s/view?usp=sharing

It didn't run on my device, but i tested it on another device it works fine. i guess the issue is with my device compatibility.
it works fine with AnimexStream-v0.2.2-universal-release which i installed earlier.
Device name - Moto E3 power
Operating sys - Marshmallow
Instruction Sets - aemeabi-v7a , armeabi

**Comment by zeeshanhussain** [comment]
@vinaydwivedi01 can you try this https://drive.google.com/file/d/1MA51WMRaPVKdfB-pNtZnoItzWMyytqkJ/view?usp=sharing . If this does not work then there is not much i can do.

**Comment by vinaydwivedi01** [comment]
> @vinaydwivedi01 can you try this https://drive.google.com/file/d/1MA51WMRaPVKdfB-pNtZnoItzWMyytqkJ/view?usp=sharing . If this does not work then there is not much i can do.

It worked don't know how but it did, thank you very much, 
but what exactly changed in this one as compared to others ?

**Comment by zeeshanhussain** [comment]
@vinaydwivedi01 I forgot to clean before building the universal APK.

**Pull request merged**
